# Generated by Django 5.0.6 on 2024-05-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveddata',
            old_name='total_positions',
            new_name='total',
        ),
        migrations.AddField(
            model_name='saveddata',
            name='positions',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
